name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Download release Pyodide
        run: |
          mkdir -p pyodide/pyodide
          wget https://github.com/pyodide/pyodide/releases/download/0.20.1a1/pyodide-build-0.20.1a1.tar.bz2
          tar xvf pyodide-build-0.20.1a1.tar.bz2 -C pyodide
          rm -rf pyodide/pyodide/node_modules # Why is this here?
      - name: Apply Pyodide patch
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yaml
          #workflow_conclusion: success
          repo: richardotis/pyodide-prebuilt
          #branch: main
          name: pyodide-dist-patch
          # Optional, directory where to extract artifact(s), defaults to current directory
          path: pyodide/pyodide
      - name: Build the JupyterLite site
        run: |
          cp README.md content
          jupyter lite build --contents content --pyodide=pyodide
      - name: Upload (dist)
        uses: actions/upload-artifact@v2
        with:
          name: jupyterlite-demo-dist-${{ github.run_number }}
          path: ./_output

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - uses: actions/download-artifact@v2
        with:
          name: jupyterlite-demo-dist-${{ github.run_number }}
          path: ./dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
